version: "3"
services:

  nginx:
    image: nginx:1.20.2
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/upfiles/:/opt/upfiles/
